workflows:
  expo-android-build:
    name: Expo Android Build
    max_build_duration: 120
    instance_type: linux_x2
    working_directory: chat-db-mobile
    environment:
      android_signing:
        - keystore_reference
      groups:
        - expo_credentials
      vars:
        EXPO_PUBLIC_API_URL: "https://meo-mv5n.onrender.com"
      node: 18.17.0
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install Expo CLI
        script: |
          npm install -g @expo/ngrok@^4.1.0
          npm install -g expo-cli
      - name: Prebuild Expo (generate native code)
        script: |
          npx expo prebuild --platform android --clean
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - mehau5lucas@gmail.com
        notify:
          success: true
          failure: true

  expo-ios-build:
    name: Expo iOS Build for AltStore
    max_build_duration: 120
    instance_type: mac_mini_m1
    working_directory: chat-db-mobile
    environment:
      groups:
        - apple_credentials
      vars:
        EXPO_PUBLIC_API_URL: "https://meo-mv5n.onrender.com"
        BUNDLE_ID: "com.lychie5.meomobile"
      node: 18.17.0
      xcode: 16.1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install Expo CLI and fastlane
        script: |
          npm install -g @expo/ngrok@^4.1.0
          npm install -g expo-cli
          gem install fastlane
      - name: Remove Push Notifications
        script: |
          node <<'EOF'
          const fs = require('fs');
          const appJson = JSON.parse(fs.readFileSync('app.json', 'utf8'));
          
          if (appJson.expo?.plugins) {
            appJson.expo.plugins = appJson.expo.plugins.filter(plugin => {
              const name = typeof plugin === 'string' ? plugin : plugin[0];
              return !name.includes('notification');
            });
          }
          
          if (appJson.expo?.ios?.infoPlist) {
            delete appJson.expo.ios.infoPlist.UIBackgroundModes;
          }
          
          fs.writeFileSync('app.json', JSON.stringify(appJson, null, 2));
          console.log('✓ Cleaned app.json');
          EOF
      - name: Prebuild Expo
        script: |
          npx expo prebuild --platform ios --clean
      - name: Detect project name
        script: |
          cd ios
          PROJECT=$(ls -d *.xcodeproj | head -n 1 | sed 's/\.xcodeproj$//')
          echo "XCODE_PROJECT=$PROJECT" >> $CM_ENV
          echo "✓ Project: $PROJECT"
          cd ..
      - name: Clean entitlements
        script: |
          find ios -name "*.entitlements" -delete
          echo "✓ Removed entitlements"
      - name: Check Podfile
        script: |
          cd ios
          echo "=== Checking Podfile ==="
          if [ -f "Podfile" ]; then
            echo "✓ Podfile exists"
            cat Podfile
          else
            echo "✗ Podfile NOT found!"
          fi
          cd ..
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          echo "=== Installing pods ==="
          pod install
          echo "=== Checking workspace ==="
          ls -la *.xcworkspace || echo "✗ No workspace found"
          ls -la
          cd ..
          echo "✓ Pods installed"
      - name: Build unsigned IPA
        script: |
          cd ios
          
          echo "=== Building app with ad-hoc signing ==="
          # Build with ad-hoc signing to execute all scripts
          xcodebuild clean archive \
            -workspace "$XCODE_PROJECT.xcworkspace" \
            -scheme "$XCODE_PROJECT" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath ../build/$XCODE_PROJECT.xcarchive \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="" \
            DEVELOPMENT_TEAM=""
          
          cd ..
          
          # Extract .app from archive
          APP=$(find build/$XCODE_PROJECT.xcarchive/Products/Applications -name "*.app" -type d | head -n 1)
          
          if [ -z "$APP" ]; then
            echo "✗ App bundle not found"
            exit 1
          fi
          
          echo "✓ App: $APP"
          
          # Ensure Info.plist is valid
          if [ ! -f "$APP/Info.plist" ]; then
            echo "✗ Missing Info.plist"
            exit 1
          fi
          
          # Read bundle ID from Info.plist
          BUNDLE=$(/usr/libexec/PlistBuddy -c "Print CFBundleIdentifier" "$APP/Info.plist" 2>/dev/null || echo "com.lychie5.meomobile")
          echo "✓ Bundle ID: $BUNDLE"
          
          # Create IPA structure
          rm -rf Payload
          mkdir Payload
          cp -R "$APP" Payload/
          
          # Create IPA (use -r for recursive, -y for symlinks)
          zip -qr meomobile.ipa Payload
          
          # Move to artifacts
          mv meomobile.ipa build/
          rm -rf Payload
          
          # Validate IPA
          if [ -f "build/meomobile.ipa" ]; then
            echo "✓ IPA created: $(ls -lh build/meomobile.ipa | awk '{print $5}')"
            
            # Quick check
            unzip -l build/meomobile.ipa | grep -q "Payload/.*\.app/Info.plist" && echo "✓ Valid structure" || echo "✗ Invalid structure"
          else
            echo "✗ IPA creation failed"
            exit 1
          fi
    artifacts:
      - build/meomobile.ipa
    publishing:
      email:
        recipients:
          - mehau5lucas@gmail.com
        notify:
          success: true
          failure: true
