workflows:
  expo-android-build:
    name: Expo Android Build
    max_build_duration: 120
    instance_type: linux_x2
    working_directory: chat-db-mobile
    environment:
      android_signing:
        - keystore_reference
      groups:
        - expo_credentials
      vars:
        EXPO_PUBLIC_API_URL: "https://meo-mv5n.onrender.com"
      node: 18.17.0
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install Expo CLI
        script: |
          npm install -g @expo/ngrok@^4.1.0
          npm install -g expo-cli
      - name: Prebuild Expo (generate native code)
        script: |
          npx expo prebuild --platform android --clean
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - mehau5lucas@gmail.com
        notify:
          success: true
          failure: true

  expo-ios-build:
    name: Expo iOS Build (Development)
    max_build_duration: 120
    instance_type: mac_mini_m1
    working_directory: chat-db-mobile
    environment:
      groups:
        - apple_credentials
      vars:
        EXPO_PUBLIC_API_URL: "https://meo-mv5n.onrender.com"
        BUNDLE_ID: "com.lychie5.meomobile"
      node: 18.17.0
      xcode: 15.2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install Expo CLI
        script: |
          npm install -g @expo/ngrok@^4.1.0
          npm install -g expo-cli
      - name: Remove Push Notifications from app.json
        script: |
          # Remove expo-notifications plugin to avoid Push Notifications capability
          node -e "
          const fs = require('fs');
          const appJson = JSON.parse(fs.readFileSync('app.json', 'utf8'));
          
          // Remove notification-related plugins
          if (appJson.expo && appJson.expo.plugins) {
            appJson.expo.plugins = appJson.expo.plugins.filter(plugin => {
              if (typeof plugin === 'string') {
                return !plugin.includes('notification');
              }
              if (Array.isArray(plugin)) {
                return !plugin[0].includes('notification');
              }
              return true;
            });
          }
          
          // Remove ios.infoPlist notification permissions
          if (appJson.expo && appJson.expo.ios && appJson.expo.ios.infoPlist) {
            delete appJson.expo.ios.infoPlist['UIBackgroundModes'];
          }
          
          fs.writeFileSync('app.json', JSON.stringify(appJson, null, 2));
          console.log('Removed Push Notifications from app.json');
          "
      - name: Prebuild Expo (generate native code)
        script: |
          npx expo prebuild --platform ios --clean
      - name: Detect Xcode project
        script: |
          cd ios
          XCODE_PROJECT=$(ls -d *.xcodeproj | head -n 1 | sed 's/\.xcodeproj$//')
          XCODE_WORKSPACE=$(ls -d *.xcworkspace | head -n 1 | sed 's/\.xcworkspace$//')
          echo "XCODE_PROJECT=$XCODE_PROJECT" >> $CM_ENV
          echo "XCODE_WORKSPACE=$XCODE_WORKSPACE" >> $CM_ENV
          echo "Detected project: $XCODE_PROJECT"
          echo "Detected workspace: $XCODE_WORKSPACE"
          cd ..
      - name: Remove Push Notifications entitlements
        script: |
          # Remove any entitlements file to avoid Push Notifications requirement
          find ios -name "*.entitlements" -type f -delete
          echo "Removed all entitlements files"
      - name: Set up provisioning profiles
        script: |
          echo "=== Setting up code signing ==="
          echo "Bundle ID: $BUNDLE_ID"
          echo "Apple ID: $APPLE_ID"
          
          # Initialize keychain for code signing
          keychain initialize
          
          # Fetch or create provisioning profile using Apple ID
          echo "Fetching signing files..."
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_DEVELOPMENT \
            --create \
            --apple-id "$APPLE_ID" \
            --password "$APP_SPECIFIC_PASSWORD" || {
              echo "Error: Failed to fetch signing files"
              echo "Make sure APPLE_ID and APP_SPECIFIC_PASSWORD are set correctly"
              exit 1
            }
          
          # Add certificates to keychain
          echo "Adding certificates to keychain..."
          keychain add-certificates
          
          # List provisioning profiles
          echo "=== Provisioning profiles installed ==="
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
          
          # Configure Xcode project to use fetched profiles
          echo "Configuring Xcode project..."
          xcode-project use-profiles
      - name: Set manual code signing
        script: |
          # Force manual code signing to avoid automatic entitlements
          cd ios
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' "$XCODE_PROJECT.xcodeproj/project.pbxproj"
          sed -i '' 's/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/g' "$XCODE_PROJECT.xcodeproj/project.pbxproj"
          # Remove any reference to entitlements
          sed -i '' '/CODE_SIGN_ENTITLEMENTS/d' "$XCODE_PROJECT.xcodeproj/project.pbxproj"
          cd ..
      - name: Build iOS app
        script: |
          cd ios
          
          # Get provisioning profile and extract Team ID properly
          PROFILE_PATH=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" -print -quit)
          
          if [ -z "$PROFILE_PATH" ]; then
            echo "Error: No provisioning profile found"
            exit 1
          fi
          
          echo "Using profile: $PROFILE_PATH"
          
          # Extract Team ID using security cms and grep
          TEAM_ID=$(security cms -D -i "$PROFILE_PATH" 2>/dev/null | grep -A 1 TeamIdentifier | grep string | sed -e 's/<string>//' -e 's/<\/string>//' -e 's/^[[:space:]]*//')
          
          if [ -z "$TEAM_ID" ]; then
            echo "Error: Could not extract Team ID from profile"
            # Try alternative method
            TEAM_ID=$(security cms -D -i "$PROFILE_PATH" 2>/dev/null | plutil -extract TeamIdentifier.0 raw - 2>/dev/null)
          fi
          
          echo "Team ID: $TEAM_ID"
          
          # Get profile UUID
          PROFILE_UUID=$(security cms -D -i "$PROFILE_PATH" 2>/dev/null | grep -A 1 UUID | grep string | sed -e 's/<string>//' -e 's/<\/string>//' -e 's/^[[:space:]]*//')
          echo "Profile UUID: $PROFILE_UUID"
          
          # Build for device with proper code signing
          xcodebuild clean build \
            -project "$XCODE_PROJECT.xcodeproj" \
            -scheme "$XCODE_PROJECT" \
            -configuration Release \
            -sdk iphoneos \
            -destination generic/platform=iOS \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="iPhone Developer" \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_UUID" \
            ONLY_ACTIVE_ARCH=NO
          
          # Create properly structured IPA
          cd ..
          APP_PATH="ios/build/Build/Products/Release-iphoneos/$XCODE_PROJECT.app"
          
          if [ ! -d "$APP_PATH" ]; then
            echo "Error: App bundle not found at $APP_PATH"
            echo "Searching for .app bundles:"
            find ios/build -name "*.app" -type d
            exit 1
          fi
          
          # Create Payload directory
          mkdir -p Payload
          cp -r "$APP_PATH" Payload/
          
          # Create IPA with proper compression
          cd Payload
          zip -r "../$XCODE_PROJECT.ipa" .
          cd ..
          rm -rf Payload
          
          echo "IPA created: $XCODE_PROJECT.ipa"
          ls -lh "$XCODE_PROJECT.ipa"
    artifacts:
      - "*.ipa"
      - ios/build/Release-iphoneos/*.app
    publishing:
      email:
        recipients:
          - mehau5lucas@gmail.com
        notify:
          success: true
          failure: true
