# ==========================================
# 🚀 Render Configuration avec Docker
# ==========================================

services:
  # Backend Web Service
  - type: web
    name: chat-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: frankfurt  # ou oregon, singapore, etc.
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: chat-db
          property: connectionString
      - key: DB_CONN_LIMIT
        value: 10
    healthCheckPath: /health

databases:
  # PostgreSQL Database
  - name: chat-db
    databaseName: chat_db
    user: chatuser
    plan: free
    region: frankfurt
