workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.mehau.chatdb"
      node: 18.17.0
    scripts:
      - name: Install npm dependencies
        script: |
          cd chat-db-mobile
          npm install
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/chat-db-mobile/android/local.properties"
      - name: Build Android APK
        script: |
          cd chat-db-mobile/android
          ./gradlew assembleRelease
    artifacts:
      - chat-db-mobile/android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - mehau@example.com
        notify:
          success: true
          failure: true

  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.mehau.chatdb
      groups:
        - app_store_connect
      vars:
        XCODE_WORKSPACE: "ChatDB.xcworkspace"
        XCODE_SCHEME: "ChatDB"
      node: 18.17.0
      xcode: 15.0
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          cd chat-db-mobile
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd chat-db-mobile/ios
          pod install
      - name: Build iOS app
        script: |
          cd chat-db-mobile/ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $HOME/Library/Developer/Xcode/Archives/ChatDB.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $HOME/Library/Developer/Xcode/Archives/ChatDB.xcarchive \
            -exportOptionsPlist chat-db-mobile/ios/ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/build
    artifacts:
      - build/*.ipa
    publishing:
      email:
        recipients:
          - mehau@example.com
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

  expo-build:
    name: Expo Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
      node: 18.17.0
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          cd chat-db-mobile
          npm install
      - name: Install Expo CLI
        script: |
          npm install -g eas-cli
      - name: Build Android with EAS
        script: |
          cd chat-db-mobile
          eas build --platform android --non-interactive --no-wait
      - name: Build iOS with EAS
        script: |
          cd chat-db-mobile
          eas build --platform ios --non-interactive --no-wait
    publishing:
      email:
        recipients:
          - mehau@example.com
        notify:
          success: true
          failure: true
